runtime: python38 # or another supported version

instance_class: F1
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /res
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto